name: C++ Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C++ environment
        run: |
          sudo apt update
          sudo apt install -y g++ make catch2

      - name: Build project
        run: |
          make clean
          make

      - name: Run tests
        run: |
          ./tests

      - name: Clean up
        run: |
          make clean
